# Generated by Django 4.0.2 on 2022-02-21 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_alter_shortener_expire_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='times_followed',
        ),
        migrations.AddField(
            model_name='shortener',
            name='duration_expire',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='shortener',
            name='expire_in',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 14, 51, 41, 309360)),
        ),
    ]
